TractorCompare/Models/Brand.cs
namespace TractorCompare.Models
{
    public class Brand
    {
        public string brandID { get; set; }
        public string name { get; set; }

    }
}

TractorCompare/Models/ErrorViewModel.cs
namespace TractorCompare.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TractorCompare/Models/Tractors.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Org.BouncyCastle.Bcpg.OpenPgp;
using System.Collections.Generic;
using System.ComponentModel;


namespace TractorCompare.Models
{
    public class Tractors
    {
        public Tractors() 
        {
        }

        public int tractorID { get; set; }
        public string brandID { get; set; }
        public string brand { get; set; }
        public string Model { get; set; }
        public string Class { get; set; }
        public string HP { get; set; }
        public string PTO { get; set; }
        public string fuel { get; set; }
        public string hydroSteer { get; set; }
        public string hydroImp { get; set; }
        public string threePT { get; set; }
        public string loaderID { get; set; }

        public string image { get; set; }
        public IEnumerable<Brand> name { get; set; }



    }
}

TractorCompare/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TractorCompare.Models;

namespace TractorCompare.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TractorCompare/Controllers/TractorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TractorCompare.Models;

namespace TractorCompare.Controllers
{
    public class TractorController : Controller
    {
        private readonly ITractorRepository repo;

        public TractorController(ITractorRepository repo)
        {
            this.repo = repo;
        }

        public IActionResult Index(string filter)
        {

            var tractors = repo.GetAllTractors();

            ViewBag.BrandSort = String.IsNullOrEmpty(filter) ? "brand_desc" : "";
            ViewBag.HPSort = String.IsNullOrEmpty(filter) ? "hp_desc" : "";
            ViewBag.ClassSort = String.IsNullOrEmpty(filter) ? "class_desc" : "";
            ViewBag.All = "All";
            ViewBag.JD = "John Deere";
            ViewBag.Kub = "Kubota";
            ViewBag.Kiot = "Kioti";
            ViewBag.Sub = "Sub";
            ViewBag.SF = "SF";
            ViewBag.SC = "SC";
            ViewBag.Com = "Com";


            switch (filter)
            {
                case "brand_desc":
                    tractors = tractors.OrderBy(t => t.brandID);
                    break;
                case "class_desc":
                    tractors = tractors.OrderBy(t => t.Class);
                    break;
                case "hp_desc":
                    tractors = tractors.OrderBy(t => t.HP);
                    break;
                case "John Deere":
                    tractors = tractors.Where(t => t.brandID.Equals("John Deere"));
                    break;
                case "Kubota":
                    tractors = tractors.Where(t => t.brandID.Equals("Kubota"));
                    break;
                case "Kioti":
                    tractors = tractors.Where(t => t.brandID.Equals("Kioti"));
                    break;
                case "Sub":
                    tractors = tractors.Where(t => t.Class.Equals("1. Sub-Compact"));
                    break;
                case "SF":
                    tractors = tractors.Where(t => t.Class.Equals("2. Small Frame"));
                    break;
                case "SC":
                    tractors = tractors.Where(t => t.Class.Equals("2. Small Compact"));
                    break;
                case "Com":
                    tractors = tractors.Where(t => t.Class.Equals("3. Compact"));
                    break;
                default:
                    tractors = tractors.OrderBy(t => t.brandID);
                    break;
            }
            return View(tractors);
        }


        public IActionResult Compare(string model1, string model2)
        {
            var tractors = from t in repo.CompareNow() select t;
            

            return View(tractors);
        }

        public IActionResult ViewTractor(int id)
        {
            var tractor = repo.GetTractor(id);

            return View(tractor);

        }

        public IActionResult UpdateTractor(int id)
        {
            Tractors make = repo.GetTractor(id);
            if (make == null)
            {
                return View("ProductNotFound");
            }
            return View(make);
        }

        public IActionResult UpdateTractorToDatabase(Tractors tractor)
        {
            repo.UpdateTractor(tractor);
            return RedirectToAction("ViewTractor", new {id = tractor.tractorID});
        }
        public IActionResult InsertTractor()
        {
            var trac = repo.AssignBrand();
            return View(trac);
        }


        public IActionResult InsertTractorToDB(Tractors newtractor) 
        {
            repo.InsertTractor(newtractor);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteTractor(Tractors tractors) 
        {
            repo.DeleteTractor(tractors);
            return RedirectToAction("Index");
        }

    }
}

TractorCompare/Views/Home/About.cshtml
<h3>About Page</h3>

<p>Tractor Compare was created as my final project for <a href="https://truecoders.io/">True Coders</a> Software Engineering program. The site was built using .Net MVC, with a database I made using MySQL. The data was gathered 
    from various manufacturers websites. C# was used as the primary programming language. I hope you enjoy this site as much as I enjoyed creating it</p>

TractorCompare/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Tractor Compare!</h1>
    <br/>
    <div class="container-fluid">
        <div class="row">
            <h5>
                Open the Tractor Table tab to view the different models of tractors.
            </h5>
            <div class="col"><img src="~/images/3r.jpg" alt="tractor" width="550" /></div>
            <div class="col"><img src="~/images/ck.jpg" alt="tractor" width="550" /></div>
        </div>
    </div>
</div>

TractorCompare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TractorCompare</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TractorCompare.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Welcome</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Tractor" asp-action="Index">Tractor Table</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TractorCompare - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TractorCompare/Views/Tractor/Compare.cshtml
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TractorCompare.styles.css" asp-append-version="true" />
</head>

@using TractorCompare.Models;
@model IEnumerable<Tractors>

<div class="container-fluid">
    <div class="row">
        <div class="col-2">
            nav bar
        </div>
        <div class="col-5">
            pick tractor 1
            <form asp-action="Compare" method="get">
                <div class="form-actions no-color">
                    <p>
                        tractor1: <input type="text" name="model1" value="@ViewData["model1"]" />
                        <input type="submit" value="Search" class="btn btn-default" /> |
                        <a asp-action="Index">Back to Full List</a>
                    </p>
                    <p>
                        @foreach (var tractor in Model)
                        {
                            <img src="@Url.Content(@tractor.image)" alt="tractor" width="250" />
                            <h1>@tractor.brandID</h1>
                            <h3>@tractor.Model</h3>
                        <p>HorsePower: @tractor.HP</p>

                    }
                    <//>

                    </div>
            </form>
        </div>
        <div class="col-5">
            pick tractor2
            <form asp-action="Compare" method="get">
                <div class="form-actions no-color">
                    <p>
                        tractor2: <input type="text" name="model1" default="1025r" value="@ViewData["model2"]" />
                        <input type="submit" value="Search" class="btn btn-default" /> |
                        <a asp-action="Index">Back to Full List</a>
                    </p>

                    <p>
                        @foreach (var tractor in Model)
                        {
                            <img src="@Url.Content(@tractor.image)" alt="tractor" width="250" />
                            <h1>@tractor.brandID</h1>
                            <h3>@tractor.Model</h3>
                            <p>HorsePower: @tractor.HP</p>

                    }
                        </p>
                    </div>
            </form>
        </div>
    </div>
</div>

TractorCompare/Views/Tractor/Index.cshtml
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TractorCompare.styles.css" asp-append-version="true" />
</head>


@using TractorCompare.Models;
@model IEnumerable<Tractors>

<div class="container-fluid">
    <div class="row">

        <div class="col-1">
            <h2>Sort by</h2>
            <div>
                <button class="btn btn-outline-primary" onclick="location.href='/Tractor/Index/'" type="button">Show All</button>
            </div>
            <br />
            <div class="dropdown">
                <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    Brands
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li>@Html.ActionLink("John Deere", "Index", new { filter = ViewBag.JD })</li>
                    <li>@Html.ActionLink("Kubota", "Index", new { filter = ViewBag.Kub })</li>
                    <li>@Html.ActionLink("Kioti", "Index", new { filter = ViewBag.Kiot })</li>
                </ul>
            </div>
            <br />
            <div class="dropdown">
                <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    Size
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li>@Html.ActionLink("Sub-Compact", "Index", new { filter = ViewBag.Sub })</li>
                    <li>@Html.ActionLink("Small Frame", "Index", new { filter = ViewBag.SF })</li>
                    <li>@Html.ActionLink("Small Compact", "Index", new { filter = ViewBag.SC })</li>
                    <li>@Html.ActionLink("Compact", "Index", new { filter = ViewBag.Com })</li>
                </ul>
            </div>
            <br />
            <div>
                <button class="btn btn-outline-info" onclick="location.href='/Tractor/InsertTractor/'" type="button">Add a new Tractor</button>
            </div>

        </div>


        


        <div class="col-11">
            <h2>Tractors</h2> <p>Click on the tractor image to view full information</p>



            <table class="table table-hover" id="TractorTable">
                <thead class="bg-light sticky-top top-0">
                    <tr>
                        <th>Image</th>
                        <!--<th>Html.ActionLink("Brand", "Index", new {class="bi bi-arrow-down-up", sortOrder = ViewBag.BrandSort})</th>-->
                        <th>Brand </th>
                        <th>Model</th>
                        <th>Series/Size</th>
                        <th>Horsepower</th>
                        <th>PTO HP</th>
                        <th>Fuel cap.</th>
                        <th>Hydraulic steering</th>
                        <th>Hydraulic implement</th>
                        <th>3pt hitch lift cap.</th>
                    </tr>

                </thead>

                @foreach (var Tractor in Model)
                {
                    <tbody>
                        <tr>
                            <td>
                                <a href=/Tractor/viewTractor/@Tractor.tractorID>
                                    <img src="@Url.Content(@Tractor.image)" alt="Tractor image not found" width="150" />
                                </a>
                            </td>
                            <td>@Tractor.brandID</td>
                            <td>@Tractor.Model</td>
                            <td>@Tractor.Class</td>
                            <td>@Tractor.HP Hp</td>
                            <td>@Tractor.PTO Hp</td>
                            <td>@Tractor.fuel Gal</td>
                            <td>@Tractor.hydroSteer Gpm</td>
                            <td>@Tractor.hydroImp Gpm</td>
                            <td>@Tractor.threePT Lbs</td>
                        </tr>
                    </tbody>
                }
            </table>
        </div>
        </div>
</div>

TractorCompare/Views/Tractor/InsertTractor.cshtml
@model Tractors


<h2>Add a new Tractor</h2>

@using (Html.BeginForm("InsertTractorToDB", "Tractor", "Post"))
{
    <input asp-for="tractorID" type="hidden" value="" />

    <div class="form-group">
        <label for="">Select a Brand</label>
        <select class="form-control" name="brandID" value="">
            @foreach (var x in Model.name)
            {
                <option value="@x.brandID"> @x.name</option>
            }
        </select>
    </div>

    <label asp-for="Model" class="control-label">Model</label>
    <input type="text" name="Model" class="form-control" value="" />

    <div class="form-group">
        <label for="">Select a size</label>
        <select class="form-control" name="Class" value="">
            <option value="1. Sub-Compact">Sub-Compact</option>
            <option value="2. Small Frame">Small Frame</option>
            <option value="2. Small Compact">Small Compact</option>
            <option value="3. Compact">Compact</option>
        </select>
    </div>

    <label asp-for="HP" class="control-label">Horse Power</label>
    <input type="number" step="0.01" name="HP" class="form-control" />

    <label asp-for="PTO" class="control-label">PTO Horsepower</label>
    <input title="PTO" type="number" step="0.01" name="PTO" class="form-control" value="@Model.PTO" />

    <label asp-for="fuel" class="control-label">Fuel capacity in gallons</label>
    <input title="fuel" type="number" step="0.01" name="fuel" class="form-control" value="@Model.fuel" />

    <label asp-for="hydroSteer" class="control-label">Hydraulic steering pump flow in gpm</label>
    <input title="hydroSteer" type="number" step="0.01" name="hydroSteer" class="form-control" value="@Model.hydroSteer" />

    <label asp-for="hydroImp" class="control-label">Hydraulic pump flow in gpm</label>
    <input title="hydroImp" type="number" step="0.01" name="hydroImp" class="form-control" value="@Model.hydroImp" />

    <label asp-for="threePT" class="control-label">three point hitch lift capacity in pounds</label>
    <input title="threePT" type="number" step="0.01" name="threePT" class="form-control" value="@Model.threePT" />


    <br />
    <input type="submit" value="Add Tractor" class="btn btn-primary" />
}

TractorCompare/Views/Tractor/UpdateTractor.cshtml
@using TractorCompare.Models;
@model Tractors

<h2>Update @Model.brandID @Model.Model</h2>

@using (Html.BeginForm("UpdateTractorToDatabase", "Tractor", "Post"))
{
    <input asp-for="tractorID" type="hidden" value="@Model.tractorID" />

    <div class="form-group">
        <label for="">Select a size</label>
        <select class="form-control" name="Class" value="">
            <option value="1. Sub-Compact">Sub-Compact</option>
            <option value="2. Small Frame">Small Frame</option>
            <option value="2. Small Compact">Small Compact</option>
            <option value="3. Compact">Compact</option>
        </select>
    </div>

    <label asp-for="HP" class="control-label">Horsepower</label>
    <input title="HP" type="number" step="0.01" name="HP" class="form-control" value="@Model.HP" />

    <label asp-for="PTO" class="control-label">PTO Horsepower</label>
    <input title="PTO" type="number" step="0.01" name="PTO" class="form-control" value="@Model.PTO" />

    <label asp-for="fuel" class="control-label">Fuel capacity in gallons</label>
    <input title="fuel" type="number" step="0.01" name="fuel" class="form-control" value="@Model.fuel" />

    <label asp-for="hydroSteer" class="control-label">Hydraulic steering pump flow in gpm</label>
    <input title="hydroSteer" type="number" step="0.01" name="hydroSteer" class="form-control" value="@Model.hydroSteer" />

    <label asp-for="hydroImp" class="control-label">Hydraulic pump flow in gpm</label>
    <input title="hydroImp" type="number" step="0.01" name="hydroImp" class="form-control" value="@Model.hydroImp" />

    <label asp-for="threePT" class="control-label">three point hitch lift capacity in pounds</label>
    <input title="threePT" type="number" step="0.01" name="threePT" class="form-control" value="@Model.threePT" />

    <input title="submit" type="submit" value="Update Tractor" class="btn btn-primary" />
}

TractorCompare/Views/Tractor/ViewTractor.cshtml
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TractorCompare.styles.css" asp-append-version="true" />
</head>

@using TractorCompare.Models;
@model Tractors

<h3>@Model.Model Information</h3>

<div class="container-fluid">
    <div class="row">
        <div class="col-6">
            <img src="@Url.Content(@Model.image)" alt="Tractor image not found" width="500" />
        </div>
        <div class="col-6">
            <h3>@Model.brandID @Model.Model</h3>
            <br />
            <p>Series/Size: @Model.Class</p>
            <p>Engine Horsepower: @Model.HP</p>
            <p>PTO Horsepower: @Model.PTO</p>
            <p>Fuel tank capacity: @Model.fuel gallons</p>
            <p>Hydraulic steering pump: @Model.hydroSteer gpm</p>
            <p>Hydraulic implement pump: @Model.hydroImp gpm</p>
            <p>Three piont hitch lift capacity: @Model.threePT Lbs</p>

        </div>
    </div>
</div>


<br />
<br />
<br />
<br />
<br />
<div class="container-fluid">
    <div class="row">
        <div class="col-2">
            <a type="button" class="btn btn-outline-info" href="/Tractor/UpdateTractor/@Model.tractorID" >Update Tractor</a>
        </div>
        <div class="col-2">
            @using (Html.BeginForm("DeleteTractor", "Tractor", "Post"))
            {
                <button class="btn btn-outline-danger" type="submit" onclick="return confirm('Are you sure?')">Delete tractor</button>
                <input type="hidden" asp-for="tractorID" value="@Model.tractorID" />

            }
        </div>
    </div>
</div>